# Generated by Django 5.2.6 on 2025-09-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Изображение'),
        ),
    ]
